### PR TITLE
Add iOS store country code

### PR DESCRIPTION
**Pull request by jochem725**
This adds the App Store country code to iOS

### CODE REVIEW

**Comment by Klaasvaak** [comment]
We would like to move from `react-native-in-app-utils` and this missing attribute is stopping us from making that move.

**Review by hyochan — APPROVED** [review]
Thanks for your contribution 👍

**Comment by ninjaboy** [comment]
@jochem725, seems like this change is causing empty fields for products to happen randomly. I have started observing this as well as many people reported in #1203. Do you have any idea on what can be causing this?

**Comment by jochem725** [comment]
@ninjaboy Yes. What happens is that countryCode somehow ends up being `nil`, everything after `nil` is not added to the NSDictionary. I created #1246 which should prevent this from happening.

**Pull request merged**
