### PR TITLE
Revert "Expose BCP47 language tag for iOS."

### PR DESCRIPTION
**Pull request by hyochan**
Reverts dooboolab/react-native-iap#344

### CODE REVIEW

**Comment by DataGreed** [comment]
why was it reverted?

**Comment by DataGreed** [comment]
@hyochan why was it reverted? It's a crucial feature

**Comment by mikefogg** [comment]
@hyochan Just wanted to check on this, is there a reason it was reverted? I need to get annual pricing in terms of months (so annual / 12) and need access to the locale (or some other method for calculating price like that). Wanted to make sure there wasn't a specific reason before I try and add it back in :)

**Comment by hyochan** [comment]
I have reverted this since it broke the previous build. Any further update can be given as long as it works on example project.

**Pull request merged**
