### PR TITLE
Fix #1760

### PR DESCRIPTION
**Pull request by Dallas62**

### CODE REVIEW

**Comment by andresesfm** [comment]
Thank you for your contribution @Dallas62

**Comment by mmajk55** [comment]
@andresesfm When we can expect for this change being released?

**Comment by andresesfm** [comment]
@mmajk55 I'm trying to stabilize the beta for 19.0.0. beta4 includes it if that makes a difference. Sorry for the inconvenience

**Comment by Dallas62** [comment]
Without this fix, getProducts and getSubscriptions throw an error on iOS.
For most developers, like happened to me, the update 8.4.0 will auto-update making a production issue.
I caught it while apple made his review (and reporting tool).
But a hotfix must be released.

**Comment by hyochan** [comment]
The version `8.+` is maintained as latest.

You can find out at https://github.com/dooboolab/react-native-iap/discussions/1777#discussioncomment-3285577

**Pull request merged**
