### PR TITLE
Expose new isReady method

### PR DESCRIPTION
**Pull request by ospfranco**
Related to #1562 and #1559

### CODE REVIEW

**Review by enricsa — APPROVED** [review]

**Review by hyochan — CHANGES_REQUESTED** [review]
Could you kindly rename `isReady` to `isReadyAndroid` if this is only `android` dependant?

**Comment by ospfranco** [comment]
There seems to be a linting issue, but I cannot find anything wrong, the actions output is also not clear... any pointers?

**Comment by ospfranco** [comment]
Ah, nvm, found the linting issue, I need to run `./gradlew googleJavaFormat`

**Review by hyochan — APPROVED** [review]
LGTM!

**Comment by Dallas62** [comment]
`undefined is not a function` Not sure the method is correctly exposed...

**Comment by Dallas62** [comment]
I guess something like:
```js
export const isReadyAndroid = (): Promise<boolean> =>
  getNativeModule(). isReadyAndroid();
```
is missing in the `src/iap.ts`

**Comment by ospfranco** [comment]
You are right, here is a new PR, please do check it carefully since I don't understand all the internals of the package

https://github.com/dooboolab/react-native-iap/pull/1604/files

**Pull request merged**
