### PR TITLE
Release 8.0.0

### PR DESCRIPTION
**Pull request by hyochan**
Bringing #1498 forward.

Migration to Kotlin from Java
Migration to swift from ObjectiveC
Fixed Amazon getProducts being called twice
Implemented fix for Promoted product on iOS
Removed Java style plugin
Updated example app to RN 0.64.

## Contributors

Co-authored-by: andresesfm andresesfm@gmail.com

### CODE REVIEW

**Comment by Daavidaviid** [comment]
I couldn't get my products from the `Configuration.storekit` file, is this normal ?

**Comment by hyochan** [comment]
@andresesfm It's been a long time. Let's release this to `8.0.0`. How do you think?

**Comment by hyochan** [comment]
So far released to `8.0.0-rc.6`. @andresesfm Do you think we can release `8.0.0`?

**Comment by andresesfm** [comment]
I think so @hyochan . So we can minimize merge conflicts between both branches

**Comment by hyochan** [comment]
> I think so @hyochan . So we can minimize merge conflicts between both branches

Let's do it 💯

**Pull request merged**
