### PR TITLE
Fix typo in README

### PR DESCRIPTION
**Pull request by shirohana**
These two fields should be exchanged, also removed trailing whitespaced.

---
By the way, may i also prettify the README file, improve readability in normal TextEditor?

### CODE REVIEW

**Comment by hyochan** [comment]
@shirohana Heya! Thanks for your contribution. Yes, you can do any favor if you can make the `readme` better!

**Comment by shirohana** [comment]
Got it ٩(｡・ω・｡)و

in editing...

**Comment by hyochan** [comment]
@shirohana How are you doing? I've been heavily updated package in this weekend because I've missed out important feature. Could you `rebase` my work and see if you've not missed out something in master?

**Comment by shirohana** [comment]
@hyochan Sorry for late updating (ノω・。)

My company just insert an urgent request during weekend and still working on that...

I'll mention you when my pr is fully ready for review :D

**Comment by hyochan** [comment]
@shirohana Thanks for comming back! Thank your time :+1:

**Pull request merged**
