### PR TITLE
update google play to 5

### PR DESCRIPTION
**Pull request by andresesfm**
This is the first step to migrate to the new Google Play SDK 5.0.0.

### CODE REVIEW

**Comment by jkfurog** [comment]
hi @andresesfm , is it possible also to use the `queryProductDetailsAsync` instead of the deprecated `querySkuDetailsAsync`? the main reason I am requesting is that the  `queryProductDetailsAsync` is now returning the promos for that subscription

**Comment by PaxLyj** [comment]
> hi @andresesfm , is it possible also to use the `queryProductDetailsAsync` instead of the deprecated `querySkuDetailsAsync`? the main reason I am requesting is that the `queryProductDetailsAsync` is now returning the promos for that subscription
> 
> thanks! :)

Also need to use `productDetails.subscriptionOfferDetails` to handle the offers of subscription, please check the [migration guide](https://developer.android.com/google/play/billing/migrate-gpblv5). Thanks!

**Comment by andresesfm** [comment]
It's now implemented @PaxLyj please take a look

**Comment by jkfurog** [comment]
hi @andresesfm I am encountering this issue after U upgrade to v9.0.0-beta

```
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file '***/node_modules/react-native-iap/android/build.gradle' line: 19

* What went wrong:
A problem occurred evaluating project ':react-native-iap'.
> Failed to apply plugin 'kotlin-android'.
   > The current Gradle version 6.7 is not compatible with the Kotlin Gradle plugin. Please use Gradle 6.7.1 or newer, or the previous version of the Kotlin plugin.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':react-native-iap'.
> compileSdkVersion is not specified. Please add it to build.gradle

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 56s
```

**Pull request merged**
