### PR TITLE
Revert the default min SDK version back to 16

### PR DESCRIPTION
**Pull request by mars-lan**
As this was the case prior to bf7da273dd2715b9f30242edc7727102e3559902

### CODE REVIEW

**Comment by dooboolab** [comment]
@mars-lan Why is this necessary? Today, minSdk that could be published to playstore is 26 i guess. Isn't it?

**Comment by dooboolab** [comment]
Do you think minSdk 21 will be ok?

**Comment by hariks789** [comment]
minimum required targetSDK is 26 not minSDK

**Comment by dooboolab** [comment]
@hariks789 yeah. I realized later. Thanks. Merged this PR already.

**Comment by hariks789** [comment]
@dooboolab thanks 👍

**Pull request merged**
