### PR TITLE
🛠️  : Fix  NativeModules.RNIapModule.getPackageName()

### PR DESCRIPTION
**Pull request by firemanx07**
this is required for deepLinkToAndroidSubscription(sku)

### CODE REVIEW

**Review by hyochan — COMMENTED** [review]
@andresesfm Could you check if this is required?

**Comment by andresesfm** [comment]
@firemanx07 Can you please tell us what you are trying to fix? It looks like you are only changing that method from Kotlin's property syntax to Java's old method call.

**Comment by firemanx07** [comment]
@andresesfm   
deepLinkToSubscriptionsAndroid(sku: string) fails in finding the right  packageName of the application  => NatvieModules.RNIapModules.getPackageName() returns undefined .

**Comment by andresesfm** [comment]
Closing in favor of: https://github.com/dooboolab/react-native-iap/pull/1748

**Pull request closed without merging**
