### PR TITLE
Release 8.0.0

### PR DESCRIPTION
**Pull request by hyochan**
Followed by #1498, this module has been re-written to `Swift` and `Kotlin` by @andresesfm .

@andresesfm I've just rebased your work, there were quite a few collisions so I hope you can double-check the codebase. Hope you to compare this `PR` with your PR in #1498.

Since I've not had much time these days, I think it is better to release first as `rc` for early users.
I will start releasing it as `react-native-iap@8.0.0-rc.1` until we think it is stable.

This `PR` is available currently with `yarn add react-native-iap@next`.

### CODE REVIEW

**Comment by hyochan** [comment]
@andresesfm Also, could you contact me through Twitter - `dooboolab` or email - `hyo@dooboolab.com`. I want to discuss further on maintenance.

**Comment by andresesfm** [comment]
I updated IapExample in the PR to reflect pointing to the rc.1. Pulling should fix the failing CI failure

Conflicts are expected as we kept accepting PRs against the old code in java and objc

**Comment by hyochan** [comment]
> I updated IapExample in the PR to reflect pointing to the rc.1. Pulling should fix the failing CI failure
> 
> Conflicts are expected as we kept accepting PRs against the old code in java and objc

Could you kindly push the commits in the current `PR`? You've already granted a permission.

In addition, I can help to resolve conflict by rebasing it to `master` branch.
Merging does not make the branches consistent 😢

**Comment by hyochan** [comment]
@andresesfm This is strange. When I remove https://github.com/dooboolab/react-native-iap/pull/1511/commits/ce9d3d2dff2d7b1f39dab466c70557c7bf1d0e90 `build_android` CI fails but when I add them again, `android_example` is failing. I might have to come back later to check why this happens.

**Comment by andresesfm** [comment]
Hello @hyochan . I fixed the problem in my PR. Can you please create RC.2?

**Comment by andresesfm** [comment]
@hyochan I followed you on Twitter, please follow me back to DM

**Comment by hyochan** [comment]
Closes via #1498

**Pull request closed without merging**
