### PR TITLE
Supporting code push

### PR DESCRIPTION
**Pull request by Rinkuk1993**
These Additional checks will help in pushing code accessing RNIap plugin to SDK that does not have the plugin in it.

I am sure this will help other developers also to push code remotely without any breakage

### CODE REVIEW

**Comment by hyochan** [comment]
@Rinkuk1993 Thank you for the contribution. This feature is definitely needed to supports phones that doesn't support `IAP`.

**Comment by Rinkuk1993** [comment]
Sure. Thanks for the feedback. I will correct the code and push again

**Comment by hyochan** [comment]
@Rinkuk1993 Could you do me one last favor? Since there is some conflict with master branch, I would like you to rebase your code to our master branch and push once more.

**Comment by Rinkuk1993** [comment]
You can check now. Rebase is done and pushed

**Pull request merged**
