### PR TITLE
Ensure connection for acknowledgement call (#895)

### PR DESCRIPTION
**Pull request by niklaskors**
I've noticed an occasional `NullPointerException` crash (https://github.com/dooboolab/react-native-iap/issues/895) on some of the acknowledgement calls.
I'm still using the older 3.0.3 version but I've noticed that this can still be a problem in later versions as well. 
I wonder why the code inside `acknowledgePurchase` isn't wrapped with `ensureConnection` like the other functions as this would solve the case of billingClient being null? (it's also missing in `consumeProduct` btw).
I haven't tested this in production but I'm pretty sure it will fix this particular issue.

### CODE REVIEW

**Comment by hyochan** [comment]
Fixes #895

**Comment by niklaskors** [comment]
Nice, thanks for checking this so quickly. Shall I create another PR to wrap the code inside `consumeProduct` with `ensureConnection` as well? I think that function might have the same problem. 
By the way, Is it easy for you to patch `3.0.3` with this fix as well? That would be really helpful :)

**Comment by hyochan** [comment]
Sure!!! Also, I don't want to do the old fork update. Why mot upgrading instead? v3 and v4 aren't very different!

**Comment by niklaskors** [comment]
Was not able to upgrade yet because I'm using react-native v0.59 which doesn't support AndroidX yet which I think is necessary for v4 right?

**Pull request merged**
