### PR TITLE
Fixed Amazon products prices parsing

### PR DESCRIPTION
**Pull request by bimusiek**
Fixes https://github.com/dooboolab/react-native-iap/issues/1190

### CODE REVIEW

**Comment by iaphub** [comment]
Hi @bimusiek,

Price parsing looks good but regarding the currency it was already implemented by detecting the user marketplace here:
https://github.com/dooboolab/react-native-iap/blob/2e69e418cfefac4e99bd6f4d8d4885d4222566a4/index.ts#L329
Can you update the PR to only keep the price formatting?

Thanks

**Comment by bimusiek** [comment]
@iaphub Done.

**Comment by iaphub** [comment]
@bimusiek Great!
@hyochan sounds good to merge on my side

**Review by hyochan — APPROVED** [review]
Thanks for the fixes 👍

**Pull request merged**
