### PR TITLE
Upgrade android billing sdk to v3

### LINKED ISSUE #1061: Google Play Billing Library 3.0
Hi,

Is there a plan to upgrade google play billing library to version 3?

[https://android-developers.googleblog.com/2020/06/meet-google-play-billing-library.html](url)

Thanks
Ram

### PR DESCRIPTION
**Pull request by hyochan**
Resolve #1061

### CODE REVIEW

**Comment by mars-lan** [comment]
Something like this is considered "breaking" and warrants a major version bump based on semver.

**Comment by hyochan** [comment]
@mars-lan Could you kindly explain further on this? How I might have to handle this in the future?

**Comment by mars-lan** [comment]
@hyochan you removed `developerIdAndroid` & `accountIdAndroid` params from `requestPurchase` & `requestSubscription` functions, which is a breaking change. Based on [SemVer](https://semver.org/) you should have bumped up the major version to `5.0.0` instead of the minor version.

**Comment by hyochan** [comment]
@mars-lan Thanks for the detail! I'll make sure for this next time 👍

**Pull request merged**
