### PR TITLE
Migrate android billing client to 4.0.0

### LINKED ISSUE #1397: Android Billing 4.0 support
Any estimation when react-native-iap will support  android billing v4.0 ?

https://developer.android.com/google/play/billing/release-notes

There some fixes related to reconnection ANR

https://github.com/android/play-billing-samples/issues/310#issuecomment-867822077

### PR DESCRIPTION
**Pull request by hyochan**
https://developer.android.google.cn/google/play/billing

Closes #1397

### CODE REVIEW

**Comment by hyochan** [comment]
@andresesfm I've just migrated `billingClient` to `4.0.0`. However, I am not sure how to correct the android ci error.

Could you guide me how to fix the lint error?

**Review by andresesfm — APPROVED** [review]
LGTM

**Comment by hyochan** [comment]
> LGTM, just need a little formating `./gradlew goJF`

Thanks for the review! Could u kindly tell how to fix the java linring? I am not sure how ro debug this

**Comment by andresesfm** [comment]
> > LGTM, just need a little formating `./gradlew goJF`
> 
> Thanks for the review! Could u kindly tell how to fix the java linring? I am not sure how ro debug this

Just do `cd android && ./gradlew goJF` and commit the changes

**Comment by hyochan** [comment]
> > > LGTM, just need a little formating `./gradlew goJF`
> > 
> > 
> > Thanks for the review! Could u kindly tell how to fix the java linring? I am not sure how ro debug this
> 
> Just do `cd android && ./gradlew goJF` and commit the changes

Actually, I've done `./gradlew verGJF` as described in `CI`. However, it throws errors without any valuable messages so I've asked a question. However, I've changed to `goJF` and it succeeded.
So now, I've changed to `goJF`.

**Pull request merged**
