### PR TITLE
Fix for missing async await.

### PR DESCRIPTION
**Pull request by JJMoon**
Add missing async, await notation. 
이거 안드로이드는 괜찮은 지 함 보셔요..

### CODE REVIEW

**Comment by dooboolab** [comment]
This should be done to android too.
[LINK](https://facebook.github.io/react-native/docs/native-modules-android)

**Comment by dooboolab** [comment]
Resolve #279

**Comment by dooboolab** [comment]
@JJMoon Can you read [this](https://stackoverflow.com/questions/44806135/why-no-return-await-vs-const-x-await)? I don't quite get why this process resolve #279.

**Comment by dooboolab** [comment]
@lwansbrough Hi. I need your help on this `PR`. Do you think we need to call another `async` and `await` to ensure the finishes of the `function`? I feel like it is quite redundant. #279 was resolved with doing this fixes but I am still not sure why we need this. Or could be a better way.

**Comment by LinusU** [comment]
This removes the return value from these functions, there was nothing wrong with them before.

Could this please be reverted?

**Comment by hyochan** [comment]
@LinusU I felt this is quite weird too. However, @JJMoon swear to god that this should be done to fix #279. I've just looked into this one and feels like this wasn't the solution and it was just `fragile linking` problem which we should just `unlink` and `link` again. What do you think @LinusU @JJMoon ?

**Comment by LinusU** [comment]
It's possible that Babel is rewriting the async function in some way that makes the Promise resolve later in the microtask scheduling queue than before, but I don't see how that could possibly affect anything 🤔

**Comment by hyochan** [comment]
@LinusU Ok. I'll try to revert this tomorrow if I don't receive any other feedback on this. Especially from @JJMoon.

**Comment by hyochan** [comment]
@LinusU Wouldn't this be fine tough?
```
async () => RNIapIos.buyProduct(sku),
```
I've just looked in the code and saw that I've already gave some updates.

**Comment by LinusU** [comment]
The `async` there won't do anything, I would recommend keeping it as `() => RNIapIos.buyProduct(sku)`

**Comment by hyochan** [comment]
@LinusU Yes. This is just another `Promise resolver`. Ok I'll change this now then.

**Comment by hyochan** [comment]
@LinusU Done it!. @JJMoon Please check if you have any opinion on this release which you've told me to make changes. Thanks.

**Comment by JJMoon** [comment]
@hyochan It looks my PR is merged. It's OK. Thanks

**Comment by hyochan** [comment]
@JJMoon That wasn't what I was saying. The changes you've made which you swear to god to make all the functions to `async`, we thought this should be reverted. Please read the previous conversations. Thanks.

**Pull request merged**
