### PR TITLE
Major refactoring of code base, including core concepts

### PR DESCRIPTION
**Pull request by lwansbrough**
This started with issue #55 and has evolved a bit to create an easier to understand IAP module. My goal was to abstract away the differences and complexities between platforms while still providing the core benefits of each. This includes changing our common terminology surrounding items, purchases, consumption, and restoration.

Very much open to suggestions.

### CODE REVIEW

**Comment by lwansbrough** [comment]
I should mention this has also been largely untested. I'm going to be testing soon though.

**Comment by dooboolab** [comment]
Thank you. I will go over it the day after tomorrow since I have some conference tomorrow. 
By the way, could you give pull request to `dev` branch? You can refer to CONTRIBUTING.md.

**Comment by Froelund** [comment]
Nice work 👍 Do you need any help?

**Comment by lwansbrough** [comment]
@Froelund We deployed these changes to production yesterday and everything seems to be working (though we don't use the consumption code.) My suggestion is that this is okay to merge, but should be tested as much as possible.

**Comment by rikur** [comment]
wow, great job! Will test this out.

**Comment by rikur** [comment]
Other than that, seems to work great! If I'm not mistaken, the responses from purchase/restore are now more streamlined and easier to use, too.

**Comment by lwansbrough** [comment]
@riku Thanks for testing! It’s definitely possible we have some bugs on iOS. I said we deployed to prod but I really meant we deployed the Android side of it to prod, still using the old version on iOS. I’ll look into the issues you found.

**Comment by lwansbrough** [comment]
@rikur Also would be helpful to know what version of iOS you’re on. Subscription type checking only works on iOS 10+ I believe.

**Comment by rikur** [comment]
@lwansbrough Running on iOS 11.x, deployment target iOS 9.0

**Pull request merged**
