### PR TITLE
Use NSError's localizedDescription instead of custom error messages

### PR DESCRIPTION
**Pull request by mars-lan**
Fixes https://github.com/dooboolab/react-native-iap/issues/290

### CODE REVIEW

**Comment by dooboolab** [comment]
Thanks for the fix. @lwansbrough if you are available, could you review shortly, if this is ok?

**Comment by lwansbrough** [comment]
If I recall correctly, the built in error descriptions are bad.

**Comment by dooboolab** [comment]
@lwansbrough Thank you for the review. What do you think @mars-lan ?

**Comment by mars-lan** [comment]
While the built-in error message may not be as informative, at least it's localized. Also trying to maintain a positional-based mapping like this seems very fragile to me. 

Since the error code is also returned, if really needed, clients can use that to display custom error messages on JS side.

**Comment by dooboolab** [comment]
@mars-lan Alright. I agree with you. Let's merge this and see how it goes.

**Pull request merged**
