### PR TITLE
Support for retrieving subscriptions in Android

### PR DESCRIPTION
**Pull request by gveeden**
Added support for retrieving subscription items from the Play Store

### CODE REVIEW

**Comment by dooboolab** [comment]
We are sorry but this has been already updated in following [commit](https://github.com/dooboolab/react-native-iap/commit/21b218e8e557bd3a0dc903e6c9ef8cbb4dedff3a).

Can you try getOwnedItem function that is supplied to android only by giving type?

**Comment by dooboolab** [comment]
@gveeden 
Sorry for late review..
I've understand what you are trying to do here but this cause problem on ios module so we are thinking of making seperate funtion to get SUBS items.

Can you try getSubscribeItems(skus) method that only exists in android?
we published npm v0.1.15.

We are trying to publish v1 version of this repo as soon as possible.

Thanks. Please tell me if there is something more you need.

**Comment by darrius** [comment]
@dooboolab really do appreciate all that you've done so far. Do you have a timeline as to when you can fix this?

**Comment by dooboolab** [comment]
@darrius 
Hi! you can use getSubscribeItems and buySubscribeItem to get and buy items for 'SUBS'.
Is this answer your question?

**Comment by darrius** [comment]
@dooboolab Thanks for the fast reply. Let me ask my colleague and get back to you!

**Comment by dooboolab** [comment]
@darrius 
Ok~ I'll close this pull request and please write issue if there are any further question!

**Pull request closed without merging**
