### PR TITLE
Fix empty subscriptions list by removing filter

### PR DESCRIPTION
**Pull request by andresesfm**
Filtering makes it impossible to get non-renewable subscriptions: https://github.com/dooboolab/react-native-iap/issues/2176

### CODE REVIEW

**Comment by Dallas62** [comment]
Hi,

Not sure if this is working.
Receiving: `{"platform":"ios"}`

**Comment by venux92** [comment]
@andresesfm Since updating to `12.4.12` my code broke.

Now getProducts returns
```[{}, {"countryCode":......}]```
With an empty object as the first element `{}`

before in `12.4.11` it was returning
```[{"countryCode":......}]```

Just to mention. I only have one in-app product `non-consumable`

Changing 
```
return items;
```

back to

```
return items.filter(
  item: Product) =>
       skus.includes(item.productId) && item.type === 'iap',
   );
``` 

fixes it.

**Comment by andresesfm** [comment]
@Dallas62 That's strange, is it all you are getting back? or do you get an additional item with that value?

**Comment by andresesfm** [comment]
@venux92 can you please post how you are calling the method? maybe you are passing an empty element in the array?

**Comment by Dallas62** [comment]
@andresesfm It's the first item of a list of three. when I request 2 subscriptions by SKU (same group).

**Comment by andresesfm** [comment]
I will take a look

**Comment by Basil-Code** [comment]
@andresesfm It's not yet fixed. getSubscriptions is returning an empty array in ios.

**Comment by andresesfm** [comment]
> @andresesfm It's not yet fixed. getSubscriptions is returning an empty array in ios.

Please open a ticket with the details.

**Comment by venux92** [comment]
@andresesfm I updated to the latest version `12.4.14` and I can confirm it works now. (Android & iOS)
I'm using `getProducts`

To reply to your question
> @venux92 can you please post how you are calling the method? maybe you are passing an empty element in the array?
 
I had only one product so I was passing `skus: [com.myapp]`

Thanks

**Comment by wxrhead** [comment]
> @andresesfm I updated to the latest version `12.4.14` and I can confirm it works now. (Android & iOS) I'm using `getProducts`
> 
> To reply to your question
> 
> > @venux92 can you please post how you are calling the method? maybe you are passing an empty element in the array?
> 
> I had only one product so I was passing `skus: [com.myapp]`
> 
> Thanks

Hi. I am getting empty array using both getProducts and getSubscriptions. Can you please help or share the code? I am stuck on it from 2 days.

**Pull request merged**
