### PR TITLE
Supported old error codes

### PR DESCRIPTION
**Pull request by Rinkuk1993**
Fixes issue : 
https://github.com/dooboolab/react-native-iap/issues/583

Did not check iOS completely due to unavailability of account. Please let me know how I can help.

### CODE REVIEW

**Comment by hyochan** [comment]
@Rinkuk1993 Thanks for your contribution! If you tell me your apple developer account, I'll add your account to our test app as a developer.

**Comment by Rinkuk1993** [comment]
Here is my Apple ID - rinkuk1993@gmail.com.

**Comment by hyochan** [comment]
@Rinkuk1993 I've just added you to `doobooTest` app.

**Comment by Rinkuk1993** [comment]
Hey, I am unable to test it. I think the account does not have developer access.
Screen Shot 2019-08-03 at 7 19 09 PM

Simulator Screen Shot - iPhone Xʀ - 2019-08-03 at 19 07 53

**Comment by hyochan** [comment]
@rikur I've added you as an `App Manager` previously it was `developer`. Could you try again?
image

**Comment by rikur** [comment]
Wrong person highlighted :)

**Comment by hyochan** [comment]
@rikur Hey sorry for the mistake :cold_sweat: @Rinkuk1993 Please see my update above.

**Comment by Rinkuk1993** [comment]
Checked. I did not get access yet.
Just in case if you missed, you can check if you have checked the option "development, certificate..." (I don't remember the sentence exactly). This should solve the issue as Xcode is checking if I have permission for provisioning profile for the account.

**Comment by hyochan** [comment]
@Rinkuk1993 Oh you are right. I will send you a development certificate via email.

**Comment by hyochan** [comment]
@Rinkuk1993 I've just sent you and email.

**Pull request merged**
